# Generated by Django 4.1.7 on 2023-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_photo',
            field=models.ImageField(blank=True, upload_to='processed_images'),
        ),
    ]
