# Generated by Django 4.1.7 on 2023-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_processed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='processed_photo',
            field=models.ImageField(null=True, upload_to='processed_images'),
        ),
    ]
