# Generated by Django 4.1.7 on 2023-03-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_processed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='processed_photo',
            field=models.ImageField(upload_to='processed_images'),
        ),
    ]
